In [1]:
from netCDF4 import Dataset
import numpy as np
from wrf import to_np, getvar, smooth2d, get_basemap, latlon_coords, interplevel
import xarray as xr
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.basemap import Basemap

In [2]:
fl = 'wrfout_d02.nc'
file = xr.open_mfdataset(fl)

In [46]:
#jaktim
#find location of array
a=np.where((file['lat'][:]>=-6.367951550722038) & (file['lat'][:]<=-6.1549962876783555)) 
b=np.where((file['lon'][:]>=106.84150263227501) &(file['lon'][:]<=106.97024866401863)) 
print(a,b)

(array([53, 54, 55], dtype=int64),) (array([64, 65], dtype=int64),)


In [48]:
file['lev']

<xarray.DataArray 'lev' (lev: 33)>
array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
       15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27., 28.,
       29., 30., 31., 32., 33.])
Coordinates:
  * lev      (lev) float64 1.0 2.0 3.0 4.0 5.0 6.0 ... 29.0 30.0 31.0 32.0 33.0
Attributes:
    long_name:  generic
    units:      level
    axis:       Z

In [11]:
file

<xarray.Dataset>
Dimensions:    (lat: 90, lev: 33, lev_2: 1, lev_3: 4, lon: 192, time: 25)
Coordinates:
  * lon        (lon) float64 101.7 101.8 101.9 101.9 ... 116.9 117.0 117.1 117.2
  * lat        (lat) float64 -10.58 -10.5 -10.43 -10.35 ... -3.6 -3.519 -3.438
  * lev        (lev) float64 1.0 2.0 3.0 4.0 5.0 ... 29.0 30.0 31.0 32.0 33.0
  * lev_2      (lev_2) float64 1.0
  * lev_3      (lev_3) float64 1.0 2.0 3.0 4.0
  * time       (time) datetime64[ns] 2020-01-01 ... 2020-01-04
Data variables:
    u          (time, lev, lat, lon) float32 dask.array<chunksize=(25, 33, 90, 192), meta=np.ndarray>
    v          (time, lev, lat, lon) float32 dask.array<chunksize=(25, 33, 90, 192), meta=np.ndarray>
    w          (time, lev, lat, lon) float32 dask.array<chunksize=(25, 33, 90, 192), meta=np.ndarray>
    ph         (time, lev, lat, lon) float32 dask.array<chunksize=(25, 33, 90, 192), meta=np.ndarray>
    phb        (time, lev, lat, lon) float32 dask.array<chunksize=(25, 33, 90, 192), meta=np.ndarray>
    t          (time, lev, lat, lon) float32 dask.array<chunksize=(25, 33, 90, 192), meta=np.ndarray>
    q2         (time, lev_2, lat, lon) float32 dask.array<chunksize=(25, 1, 90, 192), meta=np.ndarray>
    t2         (time, lev_2, lat, lon) float32 dask.array<chunksize=(25, 1, 90, 192), meta=np.ndarray>
    th2        (time, lev_2, lat, lon) float32 dask.array<chunksize=(25, 1, 90, 192), meta=np.ndarray>
    psfc       (time, lev_2, lat, lon) float32 dask.array<chunksize=(25, 1, 90, 192), meta=np.ndarray>
    u10        (time, lev_2, lat, lon) float32 dask.array<chunksize=(25, 1, 90, 192), meta=np.ndarray>
    v10        (time, lev_2, lat, lon) float32 dask.array<chunksize=(25, 1, 90, 192), meta=np.ndarray>
    qvapor     (time, lev, lat, lon) float32 dask.array<chunksize=(25, 33, 90, 192), meta=np.ndarray>
    qcloud     (time, lev, lat, lon) float32 dask.array<chunksize=(25, 33, 90, 192), meta=np.ndarray>
    qrain      (time, lev, lat, lon) float32 dask.array<chunksize=(25, 33, 90, 192), meta=np.ndarray>
    qice       (time, lev, lat, lon) float32 dask.array<chunksize=(25, 33, 90, 192), meta=np.ndarray>
    qsnow      (time, lev, lat, lon) float32 dask.array<chunksize=(25, 33, 90, 192), meta=np.ndarray>
    qgraup     (time, lev, lat, lon) float32 dask.array<chunksize=(25, 33, 90, 192), meta=np.ndarray>
    tslb       (time, lev_3, lat, lon) float32 dask.array<chunksize=(25, 4, 90, 192), meta=np.ndarray>
    smois      (time, lev_3, lat, lon) float32 dask.array<chunksize=(25, 4, 90, 192), meta=np.ndarray>
    sh2o       (time, lev_3, lat, lon) float32 dask.array<chunksize=(25, 4, 90, 192), meta=np.ndarray>
    grdflx     (time, lev_2, lat, lon) float32 dask.array<chunksize=(25, 1, 90, 192), meta=np.ndarray>
    hgt        (time, lev_2, lat, lon) float32 dask.array<chunksize=(25, 1, 90, 192), meta=np.ndarray>
    tsk        (time, lev_2, lat, lon) float32 dask.array<chunksize=(25, 1, 90, 192), meta=np.ndarray>
    rainc      (time, lev_2, lat, lon) float32 dask.array<chunksize=(25, 1, 90, 192), meta=np.ndarray>
    rainsh     (time, lev_2, lat, lon) float32 dask.array<chunksize=(25, 1, 90, 192), meta=np.ndarray>
    rainnc     (time, lev_2, lat, lon) float32 dask.array<chunksize=(25, 1, 90, 192), meta=np.ndarray>
    snownc     (time, lev_2, lat, lon) float32 dask.array<chunksize=(25, 1, 90, 192), meta=np.ndarray>
    graupelnc  (time, lev_2, lat, lon) float32 dask.array<chunksize=(25, 1, 90, 192), meta=np.ndarray>
    hailnc     (time, lev_2, lat, lon) float32 dask.array<chunksize=(25, 1, 90, 192), meta=np.ndarray>
    cldfra     (time, lev, lat, lon) float32 dask.array<chunksize=(25, 33, 90, 192), meta=np.ndarray>
    swdown     (time, lev_2, lat, lon) float32 dask.array<chunksize=(25, 1, 90, 192), meta=np.ndarray>
    glw        (time, lev_2, lat, lon) float32 dask.array<chunksize=(25, 1, 90, 192), meta=np.ndarray>
    swnorm     (time, lev_2, lat, lon) float32 dask.array<chunksize=(25, 1, 90, 192), meta=np.ndarray>
    olr 

In [13]:
rn[0]

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [12]:
#rain itu akumulatif
#rain =rainnc+rainc

rn=np.empty((25,3,2)) #define array rain accumulation, 25=time, 3=lat, 2=lon
for i in range(0,25):
    rn[i]=file['rainc'][i,0,53:56,64:66]+file['rainnc'][i,0,53:56,64:66] #sum rain #get data for [time i, lev 0, lat jaktim, lon jaktim]
    print(i)
    
rn_new=np.empty((25,3,2)) #define array rain per time 
rn_new[0]=rn[0]
for i in range(0,24):
    rn_new[i+1]=rn[i+1]-rn[i] #accumulate, (rain+1)-rain
    print(i+1)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [16]:
file['time']

<xarray.DataArray 'time' (time: 25)>
array(['2020-01-01T00:00:00.000000000', '2020-01-01T03:00:00.000000000',
       '2020-01-01T06:00:00.000000000', '2020-01-01T09:00:00.000000000',
       '2020-01-01T12:00:00.000000000', '2020-01-01T15:00:00.000000000',
       '2020-01-01T18:00:00.000000000', '2020-01-01T21:00:00.000000000',
       '2020-01-02T00:00:00.000000000', '2020-01-02T03:00:00.000000000',
       '2020-01-02T06:00:00.000000000', '2020-01-02T09:00:00.000000000',
       '2020-01-02T12:00:00.000000000', '2020-01-02T15:00:00.000000000',
       '2020-01-02T18:00:00.000000000', '2020-01-02T21:00:00.000000000',
       '2020-01-03T00:00:00.000000000', '2020-01-03T03:00:00.000000000',
       '2020-01-03T06:00:00.000000000', '2020-01-03T09:00:00.000000000',
       '2020-01-03T12:00:00.000000000', '2020-01-03T15:00:00.000000000',
       '2020-01-03T18:00:00.000000000', '2020-01-03T21:00:00.000000000',
       '2020-01-04T00:00:00.000000000'], dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 2020-01-01 2020-01-01T03:00:00 ... 2020-01-04
Attributes:
    standard_name:  time

In [17]:
tgl=[]
for i in range(0,25,8):
    tgl.append(file['time'][i]) #array date

In [8]:
file['time'][0:6]
#dd/mm/yy hh:mm am/pm

<xarray.DataArray 'time' (time: 6)>
array(['2020-01-01T00:00:00.000000000', '2020-01-01T03:00:00.000000000',
       '2020-01-01T06:00:00.000000000', '2020-01-01T09:00:00.000000000',
       '2020-01-01T12:00:00.000000000', '2020-01-01T15:00:00.000000000'],
      dtype='datetime64[ns]')
Coordinates:
  * time     (time) datetime64[ns] 2020-01-01 ... 2020-01-01T15:00:00
Attributes:
    standard_name:  time

In [4]:
file['t']

<xarray.DataArray 't' (time: 25, lev: 33, lat: 90, lon: 192)>
dask.array<open_dataset-a1ddfd129264a1d4b8ad7553637a5d87t, shape=(25, 33, 90, 192), dtype=float32, chunksize=(25, 33, 90, 192), chunktype=numpy.ndarray>
Coordinates:
  * lon      (lon) float64 101.7 101.8 101.9 101.9 ... 116.9 117.0 117.1 117.2
  * lat      (lat) float64 -10.58 -10.5 -10.43 -10.35 ... -3.6 -3.519 -3.438
  * lev      (lev) float64 1.0 2.0 3.0 4.0 5.0 6.0 ... 29.0 30.0 31.0 32.0 33.0
  * time     (time) datetime64[ns] 2020-01-01 2020-01-01T03:00:00 ... 2020-01-04
Attributes:
    long_name:  perturbation potential temperature theta-t0 (K)

In [18]:
data=np.empty((5,5)) #define array, 5=numb of parameter, 5=time
j=0
data[0,j]=np.nanmean(file['u'][0:6,0,53:56,64:66]) #get data zonal wind for [time i, lev 0, lat jaktim, lon jaktim]
data[1,j]=np.nanmean(file['v'][0:6,0,53:56,64:66]) #get data meridional wind for [time i, lev 0, lat jaktim, lon jaktim]
data[2,j]=np.nanmean(file['t'][0:6,0,53:56,64:66]) #get data temperature for [time i, lev 0, lat jaktim, lon jaktim]
data[3,j]=np.nanmean(file['rh'][0:6,0,53:56,64:66]) #get relative humidity for [time i, lev 0, lat jaktim, lon jaktim]
data[4,j]=np.nanmean(rn_new[0:6])

In [19]:
for i in range(0,25,8):
    j=j+1
    data[0,j]=np.nanmean(file['u'][6+i:13+i+1,0,53:56,64:66])
    data[1,j]=np.nanmean(file['v'][6+i:13+i+1,0,53:56,64:66])
    data[2,j]=np.nanmean(file['t'][6+i:13+i+1,0,53:56,64:66])
    data[3,j]=np.nanmean(file['rh'][6+i:13+i+1,0,53:56,64:66])
    data[4,j]=np.nanmean(rn_new[6+i:13+i+1])

<ipython-input-19-913f1b3c9ee7>:3: RuntimeWarning: Mean of empty slice
  data[0,j]=np.nanmean(file['u'][6+i:13+i+1,0,53:56,64:66])
<ipython-input-19-913f1b3c9ee7>:4: RuntimeWarning: Mean of empty slice
  data[1,j]=np.nanmean(file['v'][6+i:13+i+1,0,53:56,64:66])
<ipython-input-19-913f1b3c9ee7>:5: RuntimeWarning: Mean of empty slice
  data[2,j]=np.nanmean(file['t'][6+i:13+i+1,0,53:56,64:66])
<ipython-input-19-913f1b3c9ee7>:6: RuntimeWarning: Mean of empty slice
  data[3,j]=np.nanmean(file['rh'][6+i:13+i+1,0,53:56,64:66])
<ipython-input-19-913f1b3c9ee7>:7: RuntimeWarning: Mean of empty slice
  data[4,j]=np.nanmean(rn_new[6+i:13+i+1])


In [20]:
data_=pd.concat([pd.DataFrame(tgl),pd.DataFrame(data[:,:4]).T],axis=1) #to dataframe #take data for time 0-4

In [22]:
data_.to_csv('coba.csv') #save

In [171]:
data_

0         0         1  \
0  <xarray.DataArray 'time' ()>\narray('2020-01-0...  2.402062 -0.137250   
1  <xarray.DataArray 'time' ()>\narray('2020-01-0...  3.258234  0.026186   
2  <xarray.DataArray 'time' ()>\narray('2020-01-0...  5.429451 -0.301333   
3  <xarray.DataArray 'time' ()>\narray('2020-01-0...  4.509379  0.894934   

          2          3         4  
0 -1.265602  81.217957  3.068188  
1  0.111431  73.953255  1.403570  
2  0.447938  74.070541  0.703395  
3 -1.340805  84.733986  0.040064